---
- name: add_redis_user
  user:
    comment: "add redis user"
    name: redis
    createhome: false
    shell: /sbin/nologin
    state: present
  tags:
    - add_redis_user
    
    
- name: create data dir
  file: 
    path: /data/redis/conf
    state: directory
    owner: redis
    group: redis
    mode: 0755
  tags:
    - mkdir_redis_conf_file



- name: copy_redis_conf
  template:
    src: redis.conf.j2
    dest: /data/redis/conf/redis-{{ item.port }}.conf
    owner: redis
    group: redis
  with_items:
    - "{{ redis_list }}"
  tags:
    - copy_redis_conf


- name: copy_redis_bin
  copy:
    src: "{{ item }}"
    dest: /data/redis/src/
    owner: redis
    group: redis
    mode: 0755
  with_items:
    - "{{ redis_bin }}"
  tags:
    - copy_redis_bin


- name: copy_redis_server
  shell:  chdir=/data/redis/src cp redis-server  redis-{{ item.port}}server
  with_items:
    - "{{ redis_list }}"
  tags:
    - copy_redis_server


- name : make_log_dir
  file: 
    path: /data/redis/log
    state: directory
  tags: 
    - make_log_dir

- name : make_data_dir
  file: 
    path: /data/redis/data/redis-{{item.port}}
    state: directory
  with_items: 
    - "{{ redis_list}}"
  tags: 
    - make_data_dir

- name: start_redis_service
  shell: /data/redis/src/redis-server /data/redis/conf/redis-{{item.port}}.conf
  with_items:
    - "{{ redis_list }}"
  tags: start_redis_service

- name: create_cluster
  shell: echo "yes" | /data/redis/src/redis-cli --cluster create  {% for item in redis_cluster_ip %} {{item}}:{{mport}} {% endfor %} {% for item in redis_cluster_ip %} {{item}}:{{sport}} {% endfor %}  --cluster-replicas 1
  when: master is defined
