- name: add localhost4
  local_action: shell echo "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4" > {{AnsibleDir}}/templates/hosts.j2
  run_once: true
- name: add localhost6
  local_action: shell echo "::1  localhost localhost.localdomain localhost6 localhost6.localdomain6" >> {{AnsibleDir}}/templates/hosts.j2
  run_once: true
- set_fact: ipaddress={{  inventory_hostname }}
- set_fact: hostname={{ ansible_hostname }}
- name: add host record
  local_action: shell echo {{ipaddress}} {{hostname}} >> {{AnsibleDir}}/templates/hosts.j2
- name: copy hosts.j2 to all 
  template: src={{AnsibleDir}}/templates/hosts.j2 dest=/etc/hosts
- name: rename host_name
  shell: hostnamectl set-hostname  {{ ansible_hostname }}
